version: '3'

services:
  node1:
    build:
      context: ./nodes/node1
    ports:
      - "8081:8080"
    environment:
      - NODE_ID=web-node-1
      - MEMORY_LIMIT_MB=1024
    restart: unless-stopped

  node2:
    build:
      context: ./nodes/node2
    ports:
      - "8082:8080"
    environment:
      - NODE_ID=db-node-1
      - MEMORY_LIMIT_MB=2048
    restart: unless-stopped

  node3:
    build:
      context: ./nodes/node3
    ports:
      - "8083:8080"
    environment:
      - NODE_ID=worker-node-1
      - MEMORY_LIMIT_MB=1536
    restart: unless-stopped